### ISSUE TITLE
Headers in IContext are empty when hot function is called again

### ISSUE THREAD

**Issue by totollygeek** [Daniel15/fdk-dotnet#13]
Simple example:
```
public Task<string> InvokeAsync(string input, IContext ctx, CancellationToken timedOut)
		{
			var result = new StringBuilder();

			result.AppendLine("HEADERS");
			foreach (var item in ctx.Headers)
				result.AppendLine($"{item.Key}: {item.Value}");

			return Task.FromResult(result.ToString());
		}
```

First call of function returns:
```
HEADERS
Accept-Encoding: gzip
Host: localhost
User-Agent: Go-http-client/1.1
Content-Length: 0
Fn-Call-Id: 01DB8THKSFNG8G00GZJ0000023
Fn-Deadline: 2019-05-19T19:54:55Z
Fn-Http-H-Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Fn-Http-H-Accept-Encoding: gzip, deflate
Fn-Http-H-Accept-Language: en-US,en;q=0.5
Fn-Http-H-Dnt: 1
Fn-Http-H-Upgrade-Insecure-Requests: 1
Fn-Http-H-User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
Fn-Http-Method: GET
Fn-Http-Request-Url: http://localhost:8080/t/cs/detect
Fn-Intent: httprequest
```
Each next call while function is still "hot" (container is in paused mode) returns this:
`HEADERS`

Not sure if handling of hot functions is working at all at the moment, but this seems like a bug.

Also on the side note, the User-Agent returned in the headers is always "Go-http-client/1.1", while the actual user agent is passed in "Fn-Http-H-User-Agent". Not sure if this is by design. If not, I will open another issue for it.

**Comment by Daniel15** [comment]
Good catch. The first issue here is that I'm not properly handling the headers. I need to only get the ones prefixed with `Fn-Http-H`, and strip that from all the keys. Currently it's just passing through all the raw headers. This is not documented anywhere in the FDK docs which is likely how I missed it. I'll submit a fix for that.

However, issue with the headers being empty is really weird. The `IContext` just gets the headers directly from the HttpRequest (https://github.com/Daniel15/fdk-dotnet/blob/master/src/FnProject.Fdk/Context.cs#L49) so I'm not sure why they'd be missing.

**Comment by Daniel15** [comment]
Please try `FnProject.Fdk` version 1.0.2 once it's published (should be available in ~10 minutes), I think I've fixed both of the issues here 😄

**Comment by totollygeek** [comment]
Yeap, it seems to work now :)
Thanks a lot for the lightning fast response
