### ISSUE TITLE
DockerHub init-image needs to be updated with .NET 5.0 image

### ISSUE THREAD

**Issue by eshneken** [Daniel15/fdk-dotnet#16]
Currently the DockerHub image that the README uses (https://hub.docker.com/r/daniel15/fn-dotnet-init) hasn't been updated  with the .NET 5.0 image.  It looks like the code has been updated in this repo, the docker image just needs to be built and deployed to DockerHub so that the instructions work without modification.

**Comment by Daniel15** [comment]
Yeah, sorry, I've been meaning to push it to Docker hub, I just haven't had time to do it. I'll see if I can do it this week.

**Comment by Daniel15** [comment]
This should be available on Docker Hub now.
